// web/survey-ui-react-antd-dvd/src/components/survey/SurveyResult.js
import React, { Component } from 'react';
import styles from './SurveyResult.css';
import { Pagination, Icon, Button, Card, WingBlank, WhiteSpace, Toast } from 'antd-mobile';
import { connect } from 'dva';
import { letters } from '../../constants';
import BackTop from '../backtop/BackTop';

function SurveyResult({ dispatch, data }) {
  const page = {
    pageIndex: 1,
    pageSize: 10,
    pageTotal: 0,
    content: [],
  };
  if (!data) {
    data = { questions: [], conclusion: {} }
  }

  const changePage = (pageIndex, backTop) => {
    console.log(`changePage`)
    page.pageIndex = pageIndex;
    renderPage();
  }
  const renderPage = () => {
    const start = (page.pageIndex - 1) * page.pageSize;
    const end = start + page.pageSize;
    page.pageTotal = Math.ceil(data.questions.length / page.pageSize);
    page.content = data.questions.slice(start, end);
  }

  renderPage();

  return (
    <div>
      <WingBlank size="lg">
        <Card>
          <Card.Header
            title={<div>得分:<span className={styles.score} >{data.conclusion.score * 2}</span></div>}
          />
          <Card.Body>
            {
              data.conclusion.content
            }

          </Card.Body>
          <Card.Footer />
        </Card>
      </WingBlank>
      <WhiteSpace />
      <SurveyResultComponent page={page} changePage={changePage} />
      <WhiteSpace />
    </div>
  );
}

class SurveyResultComponent extends Component {
  constructor(props) {
    super(props);
    this.state = {
    };
  }

  onChange = (pageIndex) => {
    this.props.changePage(pageIndex);
    this.refs['backTopComponent'].scrollToTop()
    this.forceUpdate();
  }
  getRightAnswer(choices) {
    return choices.filter((c, i) => {
      c.index = letters[i];
      return c.score != 0
    }).map(c => c.index).join()
  }

  render() {
    const page = this.props.page
    return (
      <WingBlank size="lg">
        {
          page.content.map((question, i) =>

            <Card key={i}>
              <Card.Header
                title={(page.pageIndex - 1) * page.pageSize + i + 1 + '、' + question.content}
              />
              <Card.Body>
                {
                  question.choices.map((choice, j) =>
                    <div key={`${i}-${j}`}  className={`${styles.choice} ${choice.select && choice.score != 0 ? styles.rightChoiceSelected : ''}  ${choice.select && choice.score == 0 ? styles.wrongChoiceSelected : ''}`} >
                      {letters[j] + '、' + choice.content}</div>
                  )
                }
                <p className={styles.rightChoiceSelected}>正确答案: {this.getRightAnswer(question.choices)}</p>
              </Card.Body>
              <Card.Footer />
            </Card>

          )
        }
        <BackTop ref="backTopComponent" />

        <Pagination total={page.pageTotal}
          className="custom-pagination-with-icon"
          current={page.pageIndex}
          onChange={this.onChange}
          locale={{
            prevText: (<span className="arrow-align"><Icon type="left" />上一步</span>),
            nextText: (<span className="arrow-align">下一步<Icon type="right" /></span>),
          }}
        />

      </WingBlank>
    )
  }
}

function mapStateToProps(state) {
  const { data } = state.survey;
  return {
    data,
  };
}

export default connect(mapStateToProps)(SurveyResult);

// web/survey-ui-antd/src/app/survey/survey-result/survey-result.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { RestService } from '../../providers/rest.service';
import { NzMessageService } from 'ng-zorro-antd';
import { StorageService } from '../../providers/common.service';

@Component({
  selector: 'app-survey-result',
  templateUrl: './survey-result.component.html',
  styleUrls: ['./survey-result.component.css']
})
export class SurveyResultComponent implements OnInit {
  surveyRecord:any = {}
  letters = ["A","B","C","D","E","F","G","H","I","J","K","L","M","N","O","P","Q","R","S","T","U","V","X","Y","Z"];
  page: any = {
    pageIndex: 1,
    pageSize: 10,
    pageTotal: 0,
    content: [],
  }
  constructor(private rest: RestService,
    private router: Router,
    private storage: StorageService,
    private _message: NzMessageService) { }

  ngOnInit() {
    const surveyed = this.storage.get('surveyed');

    const loginUser = this.storage.get('loginUser');
    this.rest.getSurveyRecord(loginUser._id).subscribe(result => {
      if (result && result.count > 0) {
        this.surveyRecord = result.content[0];
        this.page.pageTotal = this.surveyRecord.questions.length;
        this.renderPage();
      } else if (surveyed){
        this._message.info('本台机器测试过了');
      }
    }, (error) => {
      this._message.info('获取结果失败');
    });
  }

  changePage(pageIndex, backTop) {
    console.log(`changePage`)
    this.page.pageIndex = pageIndex;
    this.renderPage();
    backTop.clickBackTop();
  }
  renderPage() {
    const start = (this.page.pageIndex-1)*this.page.pageSize;
    const end = start + this.page.pageSize;
    this.page.content = this.surveyRecord.questions.slice(start , end);
  }

  getRightAnswer(choices) {
    return choices.filter((c, i)=>{
      c.index = this.letters[i];
      return c.score!=0
    }).map(c=>c.index).join()
  }
}

<nz-card >
    <ng-template #title>
        得分:<span class="score">{{surveyRecord?.conclusion?.score}}</span>
    </ng-template>
  
    <ng-template #body>
        {{surveyRecord.conclusion?.content}}
    </ng-template>
  </nz-card>

<nz-card *ngFor="let question of page.content;let i=index;" class="survey">
    <ng-template #title>
        {{(page.pageIndex -1)* page.pageSize + i + 1}}、{{question.content}}
    </ng-template>
  
    <ng-template #body>
      <p *ngFor="let choice of question.choices;let j=index;">
        <button nz-button [nzType]="'default'" [class.right-choice-selected]="choice.select && choice.score != 0" [class.wrong-choice-selected]="choice.select && choice.score == 0" >
          <span>{{letters[j]}}、{{choice.content}}</span>
        </button>
      </p>
      <p class="margin-10 right-choice-selected">正确答案: {{getRightAnswer(question.choices)}}</p>
    </ng-template>
  </nz-card>
  <nz-back-top #backTop>
  </nz-back-top>
  <nz-pagination class="margin-10" [nzPageIndex]="page.pageIndex" [nzPageSize]="page.pageSize" nzSimple [nzTotal]="page.pageTotal" (nzPageIndexClickChange)="changePage($event, backTop)"></nz-pagination>
